<a href="https://colab.research.google.com/github/fralfaro/MAT281/blob/main/docs/labs/lab_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT281 - Laboratorio N°04

**Objetivo**: Aplicar técnicas intermedias y avanzadas de análisis de datos con pandas utilizando un caso real: el Índice de Libertad de Prensa. Este laboratorio incluye operaciones de limpieza, transformación, combinación de datos, y análisis exploratorio usando `merge`, `groupby`, `concat` y otras funciones fundamentales.



**Descripción del Dataset**

El presente conjunto de datos está orientado al análisis del **Índice de Libertad de Prensa**, una métrica internacional que evalúa el nivel de libertad del que gozan periodistas y medios de comunicación en distintos países. Este índice es recopilado anualmente por la organización **Reporteros sin Fronteras**.

La base de datos contempla observaciones por país y año, e incluye tanto el valor del índice como el ranking correspondiente. A menor puntaje en el índice, mayor nivel de libertad de prensa.

**Diccionario de variables**

| Variable     | Clase    | Descripción                                                                          |
| ------------ | -------- | ------------------------------------------------------------------------------------ |
| `codigo_iso` | carácter | Código ISO 3166-1 alfa-3 que representa a cada país.                                 |
| `pais`       | carácter | Nombre oficial del país.                                                             |
| `anio`       | entero   | Año en que se registró la medición del índice.                                       |
| `indice`     | numérico | Valor numérico del Índice de Libertad de Prensa (menor valor indica mayor libertad). |
| `ranking`    | entero   | Posición relativa del país en el ranking mundial de libertad de prensa.              |


**Fuente original y adaptación pedagógica**

* **Fuente original**: [Reporteros sin Fronteras](https://www.rsf-es.org/), recopilado y publicado a través del portal del [Banco Mundial](https://tcdata360.worldbank.org/indicators/h3f86901f?country=BRA&indicator=32416&viz=line_chart&years=2001,2019).
* **Adaptación educativa**: Los archivos han sido modificados intencionalmente para incorporar desafíos técnicos que permiten aplicar los contenidos abordados en clases, tales como limpieza de datos, normalización, detección de duplicados, y combinación de fuentes.


**Descripción de los archivos disponibles**

* **`libertad_prensa_codigo.csv`**: Contiene los pares `codigo_iso` y `pais`. Incluye intencionalmente un código ISO con dos nombres distintos de país para efectos de limpieza y validación de datos.

* **`libertad_prensa_01.csv`**: Contiene registros de los años **anteriores a 2010**. Incluye las variables `PAIS`, `ANIO`, `INDICE`, y `RANKING` con nombres de columna en **mayúsculas**.

* **`libertad_prensa_02.csv`**: Contiene registros de los años **desde 2010 en adelante**. Estructura similar al archivo anterior, con nombres de columna también en **mayúsculas**.

In [57]:
import numpy as np
import pandas as pd

# lectura de datos
archivos_anio = [
    'https://raw.githubusercontent.com/fralfaro/MAT281/main/docs/labs/data/libertad_prensa_01.csv',
    'https://raw.githubusercontent.com/fralfaro/MAT281/main/docs/labs/data/libertad_prensa_02.csv'
 ]
df_codigos = pd.read_csv('https://raw.githubusercontent.com/fralfaro/MAT281/main/docs/labs/data/libertad_prensa_codigo.csv')



### 1. Consolidación y limpieza de datos

A partir de los archivos disponibles, realice los siguientes pasos:

**a)** Cree un DataFrame llamado `df_anio` que consolide la información proveniente de los archivos **`libertad_prensa_01.csv`** y **`libertad_prensa_02.csv`**, correspondientes a distintas ventanas de tiempo. Recuerde que ambos archivos tienen nombres de columnas en mayúscula, por lo que debe normalizarlas a **minúscula** para asegurar consistencia.

**b)** Explore el archivo **`libertad_prensa_codigo.csv`** e identifique el código ISO que aparece asociado a dos nombres de país distintos. Elimine el registro que corresponda a un valor incorrecto o inconsistente, conservando solo el que considere válido.

**c)** Una vez preparados los archivos, cree un nuevo DataFrame llamado `df` que combine `df_anio` con `df_codigos`, utilizando la columna `codigo_iso` como clave. Asegúrese de realizar una unión que conserve únicamente los registros que tengan coincidencia en ambas fuentes.

> **Sugerencia**:
>
> * Para unir los archivos por filas (años), utilice la función `pd.concat([...])`.
> * Para combinar información por columnas (variables), utilice `pd.merge(...)` especificando `on='codigo_iso'`.

In [58]:
# FIXME
df1 = pd.read_csv(archivos_anio[0])
df2 = pd.read_csv(archivos_anio[1])
dups = df_codigos[df_codigos.duplicated(subset="codigo_iso")]
df_codigos = df_codigos.drop(index=180)
df1.columns = df1.columns.str.lower()
df2.columns = df2.columns.str.lower()
df_anio = pd.concat([df1, df2])
df = pd.DataFrame()
df = pd.merge(df_anio, df_codigos, on="codigo_iso")
df.head(20)

   codigo_iso  anio  indice  ranking                    pais
0         AFG  2001    35.5     59.0             Afghanistán
1         AGO  2001    30.2     50.0                  Angola
2         ALB  2001     NaN      NaN                 Albania
3         AND  2001     NaN      NaN                 Andorra
4         ARE  2001     NaN      NaN  Emiratos Árabes Unidos
5         ARG  2001    12.0      8.0               Argentina
6         ARM  2001     NaN      NaN                 Armenia
7         ATG  2001     NaN      NaN       Antigua y Barbuda
8         AUS  2001     3.5     48.0               Australia
9         AUT  2001     7.5     86.0                 Austria
10        AZE  2001    34.5     57.0              Azerbaijan
11        BDI  2001    24.5     32.0                 Burundi
12        BEL  2001     3.5     48.0                 Bélgica
13        BEN  2001     6.0     80.0                   Benin
14        BFA  2001    27.8     42.0            Burkina Faso
15        BGD  2001    43.8     72.0              Bangladesh
16        BGR  2001     9.8     98.0                Bulgaria
17        BHR  2001    23.0     28.0                 Bahrain
18        BIH  2001    12.5      9.0    Bosnia y Herzegovina
19        BLR  2001    52.2     79.0             Bielorrusia



### 2. Exploración inicial del conjunto de datos

Una vez que hayas consolidado el DataFrame final `df`, realiza un análisis exploratorio básico respondiendo las siguientes preguntas:

#### **Estructura del DataFrame**

* ¿Cuántas **filas (observaciones)** contiene el conjunto de datos?
* ¿Cuántas **columnas** tiene el DataFrame?
* ¿Cuáles son los **nombres de las columnas**?
* ¿Qué **tipo de datos** tiene cada columna?
* ¿Hay columnas con un tipo de dato inesperado (por ejemplo, fechas como strings)?

#### **Resumen estadístico**

* Genera un resumen estadístico del conjunto de datos con `.describe()`.
  ¿Qué observas sobre los valores de `indice` y `ranking`?
* ¿Qué valores mínimo, máximo y promedio tiene la columna `indice`?
* ¿Qué países presentan los valores extremos en `indice` y `ranking`?

#### **Datos faltantes**

* ¿Cuántos valores nulos hay en cada columna?
* ¿Qué proporción de observaciones tienen valores faltantes?
* ¿Hay columnas con más del 30% de datos faltantes?

#### **Unicidad y duplicados**

* ¿Cuántos países distintos (`pais`) hay en el DataFrame?
* ¿Cuántos años distintos (`anio`) hay representados?
* ¿Existen filas duplicadas (exactamente iguales)? ¿Cuántas?

#### **Validación cruzada de columnas**

* ¿Hay inconsistencias entre el país (`pais`) y su código (`codigo_iso`)?
  (por ejemplo, un mismo código ISO asociado a más de un país)

> **Sugerencia**: Apoya tu análisis con funciones como `.info()`, `.nunique()`, `.isnull().sum()`, `.duplicated()`, `.value_counts()`, entre otras.

In [59]:
print("Estructura DataFrame: ")
print("Número de filas:", df.shape[0])
print("Número de columnas:", df.shape[1])
print("Nombres de columnas:", df.columns.tolist())
print(df.dtypes)
print('\n')
print("Resumen Estadístico: ")
print(df.describe())

min_indice = df["indice"].min()
max_indice = df["indice"].max()
mean_indice = df["indice"].mean()
print('\n')
print("Mínimo indice:", min_indice)
print("Máximo indice:", max_indice)
print("Promedio indice:", mean_indice)
print('\n')
fila_indice_min = df.loc[df["indice"].idxmin()]
print("País con menor indice:")
print(fila_indice_min[["pais", "anio", "indice"]])
fila_indice_max= df.loc[df["indice"].idxmax()]
print('\n')
print("País con mayor indice:")
print(fila_indice_max[["pais", "anio", "ranking"]])
print('\n')
fila_ranking_min = df.loc[df["ranking"].idxmin()]
print("País con menor ranking:")
print(fila_ranking_min[["pais", "anio", "ranking"]])
print('\n')
fila_ranking_max = df.loc[df["ranking"].idxmax()]
print("País con mejor ranking:")
print(fila_ranking_max[["pais", "anio", "ranking"]])
print('\n')
print('Valores nulos en cada columna: ')
print(df.isnull().sum())
print('\n')
print('Proporcion valores nulos: ')
print( df.isnull().mean()*100)
print('\n')
faltantes_30 = df.isnull().mean() > 0.30
print("¿Hay columnas con más del 30% de datos faltantes?")
print(faltantes_30)
print('\n')
print("Número de países distintos:", df["pais"].nunique())
print('\n')
print("Número de años distintos:", df["anio"].nunique())
print('\n')
print("Años representados:", df["anio"].unique())
print("\n")
num_duplicadas = df.duplicated().sum()
print("Número de filas duplicadas:", num_duplicadas)
inconsistencias = df.groupby("codigo_iso")["pais"].unique()
inconsistencias = inconsistencias[inconsistencias.str.len() > 1]
print("Inconsistencias encontradas:\n", inconsistencias)

Estructura DataFrame:
Número de filas: 3060
Número de columnas: 5
Nombres de columnas: ['codigo_iso', 'anio', 'indice', 'ranking', 'pais']
codigo_iso     object
anio            int64
indice        float64
ranking       float64
pais           object
dtype: object


Resumen Estadístico:
              anio        indice        ranking
count  3060.000000   2664.000000    2837.000000
mean   2009.941176    205.782316     477.930913
std       5.786024   2695.525264    6474.935347
min    2001.000000      0.000000       1.000000
25%    2005.000000     15.295000      34.000000
50%    2009.000000     28.000000      70.000000
75%    2015.000000     41.227500     110.000000
max    2019.000000  64536.000000  121056.000000


Mínimo indice: 0.0
Máximo indice: 64536.0
Promedio indice: 205.7823160660661


País con menor indice:
pais      Dinamarca
anio           2008
indice          0.0
Name: 1304, dtype: object


País con mayor indice:
pais         Kosovo
anio           2014
ranking    120614.0
Name: 2069, dtype: object


País con menor ranking:
pais       Finlandia
anio            2001
ranking          1.0
Name: 53, dtype: object


País con mejor ranking:
pais         Kosovo
anio           2015
ranking    121056.0
Name: 2249, dtype: object


Valores nulos en cada columna:
codigo_iso      0
anio            0
indice        396
ranking       223
pais            0
dtype: int64


Proporcion valores nulos:
codigo_iso     0.000000
anio           0.000000
indice        12.941176
ranking        7.287582
pais           0.000000
dtype: float64


¿Hay columnas con más del 30% de datos faltantes?
codigo_iso    False
anio          False
indice        False
ranking       False
pais          False
dtype: bool


Número de países distintos: 179


Número de años distintos: 17


Años representados: [2001 2002 2003 2004 2005 2006 2007 2008 2009 2012 2013 2014 2015 2016
 2017 2018 2019]


Número de filas duplicadas: 0
Inconsistencias encontradas:
 Series([], Name: pais, dtype: object)




### 3. Comparación regional: países latinoamericanos

En esta sección se busca identificar cuáles son los países de América Latina que han presentado los valores extremos del **Índice de Libertad de Prensa** en cada año observado.

> Recuerda que un menor puntaje en `indice` implica mayor libertad de prensa.

#### **Tareas:**

**a)** Utilizando un ciclo `for`, recorre cada año del conjunto de datos filtrado por países latinoamericanos, y determina para cada año:

* El país con el menor valor de `indice` (mayor libertad de prensa).
* El país con el mayor valor de `indice` (menor libertad de prensa).

**b)** Resuelve la misma tarea del punto anterior utilizando un enfoque vectorizado con `groupby`, sin usar ciclos explícitos.



#### **Lista de países latinoamericanos considerada:**

```python
america = ['ARG', 'ATG', 'BLZ', 'BOL', 'BRA', 'CAN', 'CHL', 'COL', 'CRI',
           'CUB', 'DOM', 'ECU', 'GRD', 'GTM', 'GUY', 'HND', 'HTI', 'JAM',
           'MEX', 'NIC', 'PAN', 'PER', 'PRY', 'SLV', 'SUR', 'TTO', 'URY',
           'USA', 'VEN']
```

> Puedes usar esta lista para filtrar el DataFrame final por la columna `codigo_iso`.

In [60]:
# respuesta
america = ['ARG', 'ATG', 'BLZ', 'BOL', 'BRA', 'CAN', 'CHL', 'COL', 'CRI',
       'CUB', 'DOM', 'ECU', 'GRD', 'GTM', 'GUY', 'HND', 'HTI', 'JAM',
       'MEX', 'NIC', 'PAN', 'PER', 'PRY', 'SLV', 'SUR', 'TTO', 'URY',
       'USA', 'VEN']


df_america = df[df["codigo_iso"].isin(america)]

for anio in sorted(df_america["anio"].unique()):
    df_anio = df_america[df_america["anio"] == anio]

    if df_anio.empty or df_anio["indice"].isnull().all():
        print(f"Año {anio}: no hay datos válidos")
        continue

    min_fila = df_anio.loc[df_anio["indice"].idxmin()]
    max_fila = df_anio.loc[df_anio["indice"].idxmax()]

    print(f"Año {anio}:")
    print(f"  Mejor libertad (menor indice): {min_fila['codigo_iso']} ({min_fila['indice']})")
    print(f"  Peor libertad (mayor indice): {max_fila['codigo_iso']} ({max_fila['indice']})")
    print("-" * 50)

Año 2001:
  Mejor libertad (menor indice): CAN (0.8)
  Peor libertad (mayor indice): CUB (90.3)
--------------------------------------------------
Año 2002:
  Mejor libertad (menor indice): TTO (1.0)
  Peor libertad (mayor indice): CUB (97.83)
--------------------------------------------------
Año 2003:
  Mejor libertad (menor indice): TTO (2.0)
  Peor libertad (mayor indice): ARG (35826.0)
--------------------------------------------------
Año 2004:
  Mejor libertad (menor indice): TTO (2.0)
  Peor libertad (mayor indice): CUB (87.0)
--------------------------------------------------
Año 2005:
  Mejor libertad (menor indice): BOL (4.5)
  Peor libertad (mayor indice): CUB (95.0)
--------------------------------------------------
Año 2006:
  Mejor libertad (menor indice): CAN (4.88)
  Peor libertad (mayor indice): CUB (96.17)
--------------------------------------------------
Año 2007:
  Mejor libertad (menor indice): CAN (3.33)
  Peor libertad (mayor indice): CUB (88.33)
--------------------------------------------------
Año 2008:
  Mejor libertad (menor indice): CAN (3.7)
  Peor libertad (mayor indice): CUB (94.0)
--------------------------------------------------
Año 2009:
  Mejor libertad (menor indice): USA (6.75)
  Peor libertad (mayor indice): CUB (78.0)
--------------------------------------------------
Año 2012:
  Mejor libertad (menor indice): JAM (9.88)
  Peor libertad (mayor indice): CUB (71.64)
--------------------------------------------------
Año 2013:
  Mejor libertad (menor indice): JAM (10.9)
  Peor libertad (mayor indice): CUB (70.92)
--------------------------------------------------
Año 2014:
  Mejor libertad (menor indice): CAN (10.99)
  Peor libertad (mayor indice): CUB (70.21)
--------------------------------------------------
Año 2015:
  Mejor libertad (menor indice): CRI (11.1)
  Peor libertad (mayor indice): CUB (70.23)
--------------------------------------------------
Año 2016: no hay datos válidos
Año 2017:
  Mejor libertad (menor indice): CRI (11.93)
  Peor libertad (mayor indice): CUB (71.75)
--------------------------------------------------
Año 2018:
  Mejor libertad (menor indice): JAM (11.33)
  Peor libertad (mayor indice): CUB (68.9)
--------------------------------------------------
Año 2019:
  Mejor libertad (menor indice): JAM (11.13)
  Peor libertad (mayor indice): CUB (63.81)
--------------------------------------------------

In [61]:
america = ['ARG', 'ATG', 'BLZ', 'BOL', 'BRA', 'CAN', 'CHL', 'COL', 'CRI',
           'CUB', 'DOM', 'ECU', 'GRD', 'GTM', 'GUY', 'HND', 'HTI', 'JAM',
           'MEX', 'NIC', 'PAN', 'PER', 'PRY', 'SLV', 'SUR', 'TTO', 'URY',
           'USA', 'VEN']


df_america = df[df["codigo_iso"].isin(america)]

min_idx = df_america.groupby("anio")["indice"].idxmin()
max_idx = df_america.groupby("anio")["indice"].idxmax()

min_idx = min_idx.dropna().astype(int)
max_idx = max_idx.dropna().astype(int)

mejores = df_america.loc[min_idx, ["anio", "codigo_iso", "indice"]]\
    .rename(columns={"codigo_iso": "mejor_pais", "indice": "mejor_indice"})
peores = df_america.loc[max_idx, ["anio", "codigo_iso", "indice"]]\
    .rename(columns={"codigo_iso": "peor_pais", "indice": "peor_indice"})


resumen = pd.merge(mejores, peores, on="anio").sort_values("anio")
print(resumen)

    anio mejor_pais  mejor_indice peor_pais  peor_indice
0   2001        CAN          0.80       CUB        90.30
1   2002        TTO          1.00       CUB        97.83
2   2003        TTO          2.00       ARG     35826.00
3   2004        TTO          2.00       CUB        87.00
4   2005        BOL          4.50       CUB        95.00
5   2006        CAN          4.88       CUB        96.17
6   2007        CAN          3.33       CUB        88.33
7   2008        CAN          3.70       CUB        94.00
8   2009        USA          6.75       CUB        78.00
9   2012        JAM          9.88       CUB        71.64
10  2013        JAM         10.90       CUB        70.92
11  2014        CAN         10.99       CUB        70.21
12  2015        CRI         11.10       CUB        70.23
13  2017        CRI         11.93       CUB        71.75
14  2018        JAM         11.33       CUB        68.90
15  2019        JAM         11.13       CUB        63.81

### 4. Análisis anual del índice por país

En esta sección se busca analizar la evolución del **índice máximo** de libertad de prensa alcanzado por cada país a lo largo del tiempo.

#### **Tarea principal:**

* Construye una tabla dinámica (`pivot_table`) donde las **filas** correspondan a los países, las **columnas** a los años (`anio`) y los **valores** sean el `indice` máximo alcanzado por cada país en ese año.
* Asegúrate de reemplazar los valores nulos resultantes con `0`.

> **Hint**: Puedes utilizar el parámetro `fill_value=0` en `pd.pivot_table(...)`.



#### **Preguntas adicionales:**

**a)** ¿Qué país tiene el mayor valor de `indice` en toda la tabla resultante? ¿Y cuál tiene el menor (distinto de cero)?
**b)** ¿Qué años presentan en promedio los valores de `indice` más altos? ¿Y los más bajos?

> (Pista: usa `.mean(axis=0)` sobre la tabla pivot)

**c)** ¿Qué país muestra mayor **variabilidad** (diferencia entre su máximo y mínimo `indice` a lo largo del tiempo)?

> (Pista: aplica `.max(axis=1) - .min(axis=1)`)

**d)** ¿Existen países con índice constante a lo largo de todos los años registrados? ¿Cuáles?

**e)** ¿Qué países no tienen ningún dato (es decir, quedaron con todos los valores igual a 0)? ¿Podrías explicar por qué?

In [62]:
america = ['ARG', 'ATG', 'BLZ', 'BOL', 'BRA', 'CAN', 'CHL', 'COL', 'CRI',
           'CUB', 'DOM', 'ECU', 'GRD', 'GTM', 'GUY', 'HND', 'HTI', 'JAM',
           'MEX', 'NIC', 'PAN', 'PER', 'PRY', 'SLV', 'SUR', 'TTO', 'URY',
           'USA', 'VEN']

df_america = df[df["codigo_iso"].isin(america)]

df_america = df_america.dropna(subset=["indice"])

tabla_pivot = pd.pivot_table(
    df_america,
    values="indice",
    index="codigo_iso",
    columns="anio",
    aggfunc="max",
    fill_value=0
)
max_por_pais = tabla_pivot.max(axis=1)

pais_max = max_por_pais.idxmax()
valor_max = max_por_pais.max()

pais_min = max_por_pais[max_por_pais > 0].idxmin()
valor_min = max_por_pais[max_por_pais > 0].min()

print(f"País con mayor índice: {pais_max} ({valor_max})")
print(f"País con menor índice: {pais_min} ({valor_min})")

prom = tabla_pivot.mean(axis=0)
anio_max = prom.idxmax()
prom_max = prom.max()

anio_min = prom.idxmin()
prom_min = prom.min()
print(f"Año con promedio más alto de índice: {anio_max} ({prom_max:.2f})")
print(f"Año con promedio más bajo de índice: {anio_min} ({prom_min:.2f})")

var_pais = (tabla_pivot.max(axis=1) - tabla_pivot.min(axis=1))
anio_var_max = var_pais.idxmax()
var_max = var_pais.max()

anio_var_min = var_pais.idxmin()
var_min = var_pais.min()

print(f"Pais con variabilidad mas alta: {anio_var_max} ({var_max:.2f})")
print(f"Pais con variabilidad mas baja: {anio_var_min} ({var_min:.2f})")

min_por_pais = tabla_pivot.min(axis=1)
pais_cte = max_por_pais[max_por_pais == min_por_pais].index.tolist()
print("Países con índice constante:", pais_cte)
sin_datos = tabla_pivot[(tabla_pivot == 0).all(axis=1)].index.tolist()
print("Países sin ningún dato:", sin_datos)
print("No hay ningun país que quede con todos 0, pero puede pasar porque usamos fill_value=0 para crear la tabla pivot, entonces todos los Nan se reemplazaron por 0, es decir, que si el país no tenia datos registrados, queda con puros ceros. ")
tabla_pivot

País con mayor índice: ARG (35826.0)
País con menor índice: GRD (12.0)
Año con promedio más alto de índice: 2003 (1251.68)
Año con promedio más bajo de índice: 2001 (12.42)
Pais con variabilidad mas alta: ARG (35814.67)
Pais con variabilidad mas baja: CRI (10.18)
Países con índice constante: []
Países sin ningún dato: []
No hay ningun país que quede con todos 0, pero puede pasar porque usamos fill_value=0 para crear la tabla pivot, entonces todos los Nan se reemplazaron por 0, es decir, que si el país no tenia datos registrados, queda con puros ceros.

anio,2001,2002,2003,2004,2005,2006,2007,2008,2009,2012,2013,2014,2015,2017,2018,2019
codigo_iso,,,,,,,,,,,,,,,,
ARG,12.0,15.17,35826.00,13.67,17.30,24.83,14.08,11.33,16.35,25.67,25.27,26.11,25.09,25.07,26.05,28.30
ATG,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20.81,0.00,0.00,0.00,0.00,0.00
BLZ,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.05,18.54,20.61,23.43,24.55,27.50
BOL,14.5,9.67,20.00,9.67,4.50,21.50,28.20,24.17,28.13,32.80,31.04,31.29,31.78,33.88,32.45,35.38
BRA,18.8,16.75,16.50,14.50,17.17,25.25,18.00,15.88,16.60,32.75,34.03,31.93,32.62,33.58,31.20,32.79
CAN,0.8,1.83,3.33,4.50,4.50,4.88,3.33,3.70,7.00,12.69,10.99,10.99,15.26,16.53,15.28,15.69
CHL,6.5,6.83,10.00,11.75,11.63,12.13,11.50,10.50,10.50,26.24,25.80,23.00,19.23,20.53,22.69,25.65
COL,40.8,49.17,47.38,40.17,44.75,42.33,35.50,40.13,51.50,37.48,36.68,39.08,44.11,41.47,41.03,42.82
CRI,4.3,3.83,7.63,8.50,6.67,6.50,5.10,8.00,8.08,12.08,12.23,12.26,11.10,11.93,14.01,12.24
CUB,90.3,97.83,106.83,87.00,95.00,96.17,88.33,94.00,78.00,71.64,70.92,70.21,70.23,71.75,68.90,63.81
DOM,0.0,17.00,6.75,12.25,12.75,22.75,18.00,26.83,26.13,28.34,27.17,27.31,27.90,26.76,26.79,27.90
ECU,5.5,7.67,16.50,21.75,15.25,18.50,15.50,20.00,27.50,34.69,31.16,33.65,33.21,33.64,30.56,31.88
GRD,0.0,0.00,12.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
GTM,27.3,30.83,16.50,21.50,21.25,33.00,22.64,29.50,20.25,29.39,36.61,37.92,38.03,39.33,36.17,35.94
GUY,0.0,0.00,0.00,0.00,0.00,0.00,19.75,10.50,16.63,27.08,27.08,27.21,27.07,26.80,26.25,26.63
HND,0.0,14.17,11.75,18.00,14.50,25.50,21.50,42.00,51.13,36.92,37.14,39.27,44.62,43.75,45.23,48.53
HTI,36.5,31.00,42.13,33.50,19.50,23.50,15.13,15.00,16.38,24.09,23.53,25.08,24.66,26.36,26.82,29.00
JAM,0.0,3.33,4.17,7.50,5.50,8.63,4.88,4.75,7.67,9.88,10.90,11.18,12.45,12.73,11.33,11.13
MEX,24.8,17.67,27.83,45.50,45.83,53.63,46.13,48.25,47.50,45.30,45.04,43.69,49.33,48.97,48.91,46.78
NIC,0.0,6.50,11.67,15.25,15.50,14.25,12.50,16.75,22.33,28.31,27.70,27.94,28.82,31.01,30.41,35.53
PAN,15.5,9.75,14.50,15.00,9.50,17.88,11.83,14.50,21.83,32.95,30.20,28.98,30.59,32.12,30.56,29.78
PER,9.5,10.25,40.00,33.33,28.25,37.38,26.25,20.88,30.00,31.87,31.70,31.21,29.99,30.98,30.27,30.22
PRY,8.5,7.17,10.50,15.50,18.25,26.10,20.50,14.33,16.25,28.78,31.81,33.74,33.63,35.64,32.32,32.40
SLV,8.8,6.83,6.00,5.75,10.00,20.20,12.80,17.25,15.83,22.86,21.57,23.66,27.20,27.24,27.78,29.81
SUR,0.0,0.00,0.00,0.00,0.00,0.00,6.00,10.60,11.50,18.19,18.20,18.20,16.70,16.07,16.44,16.38
TTO,0.0,1.00,2.00,2.00,5.00,5.00,6.13,7.00,8.50,23.12,23.28,22.39,23.29,20.62,22.79,24.74
URY,6.0,4.00,10.00,9.75,13.75,11.75,8.33,7.63,11.75,15.92,16.08,15.94,15.88,17.43,15.56,16.06
USA,4.8,6.00,4.00,9.50,13.00,14.50,8.00,4.00,6.75,18.22,23.49,24.41,22.49,23.88,23.73,25.69
VEN,25.0,27.83,24.63,23.00,29.00,36.88,27.33,39.50,47.33,34.44,35.37,40.61,44.77,42.94,46.03,49.10